### ISSUE TITLE
Problemas con URLs largos

### ISSUE THREAD

**Issue by JJ** [psicobyte/sluger#4]
Según nos han informado del CICODE http://cicode.ugr.es/pages/tablon/*/noticias-22/conoce-la-experiencia-en-honduras-de-un-grupo-de-estudiantes-y-profesores-voluntariosas-de-la-ugr-que-obtuvieron-la-ayuda-para-realizar-voluntariado-internacional-en-un-proyecto-de-cooperacion-para-el-desarrollo

**Comment by JJ** [comment]
Un día échale un vistazo a esto... O lo hacemos aquí on the fly.

**Comment by psicobyte** [comment]
Está resuelto en el commit https://github.com/psicobyte/sluger/commit/729575272507e0711ed1624b320e3b51792d4a96, pensé que lo había cerrado
